server:
  port: 9191
  
spring:  application:    name: zuul-proxy
    
eureka:  client:    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
zuul:
  prefix: /app
  routes:
      test:        path: /redirect/**
        location: http://www.google.co.in
      emp-service:
        path: /service/**
        location: emp-data-service 
      hr-app:
        path: /client/**
        location: hr-app 
  