server:
  port: 8888
spring:
 application:
  name: EmpService
 cloud:
    zookeeper:
      enabled: true
      connect-string: localhost:2181
      config:
        watcher:
          enabled: true
 config:
    import: "zookeeper:"
    
# datasource:
#  driver_class_name: org.mariadb.jdbc.Driver
#  url: jdbc:mariadb://localhost:3306/springdb
#  username: root
#  password: root
 jpa:
   show_sql: true

 cache:
   ehcache:
     config: "classpath:config/ehcache.xml"
# cache:
#    cache-names: "cache1,cache2"
#    caffeine:
#      spec: "maximumSize=500,expireAfterAccess=600s"

management:
 endpoints:
  web:
   exposure:
    include: "*"