app:
 datasource:
  driver_class_name: org.mariadb.jdbc.Driver
  jdbc-url: jdbc:mariadb://localhost:3306/springdb
  username: root
  password: root
  #type: org.springframework.jdbc.datasource.DriverManagerDatasource
  
#logging:
# level:
#  org.springframework: debug

spring:
 jpa:
  show_sql: true   
