spring:
 application:
   name: emp-service
 datasource:
  driver_class_name: org.mariadb.jdbc.Driver
  url: jdbc:mariadb://localhost:3306/springdb
  username: root
  password: root
 jpa:
   show_sql: true

 cache:
   ehcache:
     config: "classpath:config/ehcache.xml"
# cache:
#    cache-names: "cache1,cache2"
#    caffeine:
#      spec: "maximumSize=500,expireAfterAccess=600s"

eureka:
 client:
    register-with-eureka: true
    service-url:
     defaultZone: http://localhost:8761/eureka